const data = [
  {
    Title: "Superman",
    Year: "1978",
    Rated: "PG",
    Released: "15 Dec 1978",
    Runtime: "143 min",
    Genre: "Action, Adventure, Drama",
    Director: "Richard Donner",
    Writer: "Jerry Siegel, Joe Shuster, Mario Puzo",
    Actors: "Christopher Reeve, Margot Kidder, Gene Hackman",
    Plot: "An alien orphan is sent from his dying planet to Earth, where he grows up to become his adoptive home's first and greatest superhero.",
    Language: "English",
    Country: "United States, United Kingdom, Canada, Switzerland, France",
    Awards: "Won 1 Oscar. 17 wins & 23 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMzA0YWMwMTUtMTVhNC00NjRkLWE2ZTgtOWEzNjJhYzNiMTlkXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.3/10" },
      { Source: "Rotten Tomatoes", Value: "94%" },
      { Source: "Metacritic", Value: "81/100" },
    ],
    Metascore: "81",
    imdbRating: "7.3",
    imdbVotes: "167,329",
    imdbID: "tt0078346",
    Type: "movie",
    DVD: "01 May 2001",
    BoxOffice: "$134,451,603",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Venom",
    Year: "2018",
    Rated: "PG-13",
    Released: "05 Oct 2018",
    Runtime: "112 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Ruben Fleischer",
    Writer: "Jeff Pinkner, Scott Rosenberg, Kelly Marcel",
    Actors: "Tom Hardy, Michelle Williams, Riz Ahmed",
    Plot: "A failed reporter is bonded to an alien entity, one of many symbiotes who have invaded Earth. But the being takes a liking to Earth and decides to protect it.",
    Language: "English, Mandarin, Malay",
    Country: "China, United States",
    Awards: "3 wins & 9 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzAwNzUzNjY4MV5BMl5BanBnXkFtZTgwMTQ5MzM0NjM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.7/10" },
      { Source: "Rotten Tomatoes", Value: "30%" },
      { Source: "Metacritic", Value: "35/100" },
    ],
    Metascore: "35",
    imdbRating: "6.7",
    imdbVotes: "416,343",
    imdbID: "tt1270797",
    Type: "movie",
    DVD: "18 Jun 2019",
    BoxOffice: "$213,515,506",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Gravity",
    Year: "2013",
    Rated: "PG-13",
    Released: "04 Oct 2013",
    Runtime: "91 min",
    Genre: "Adventure, Drama, Sci-Fi",
    Director: "Alfonso Cuarón",
    Writer: "Alfonso Cuarón, Jonás Cuarón",
    Actors: "Sandra Bullock, George Clooney, Ed Harris",
    Plot: "Two astronauts work together to survive after an accident leaves them stranded in space.",
    Language: "English, Greenlandic",
    Country: "United Kingdom, United States, Mexico",
    Awards: "Won 7 Oscars. 238 wins & 187 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNjE5MzYwMzYxMF5BMl5BanBnXkFtZTcwOTk4MTk0OQ@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.7/10" },
      { Source: "Rotten Tomatoes", Value: "96%" },
      { Source: "Metacritic", Value: "96/100" },
    ],
    Metascore: "96",
    imdbRating: "7.7",
    imdbVotes: "793,228",
    imdbID: "tt1454468",
    Type: "movie",
    DVD: "25 Feb 2014",
    BoxOffice: "$274,092,705",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Inception",
    Year: "2010",
    Rated: "PG-13",
    Released: "16 Jul 2010",
    Runtime: "148 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan",
    Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
    Plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
    Language: "English, Japanese, French",
    Country: "United Kingdom, United States",
    Awards: "Won 4 Oscars. 157 wins & 220 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.8/10" },
      { Source: "Rotten Tomatoes", Value: "87%" },
      { Source: "Metacritic", Value: "74/100" },
    ],
    Metascore: "74",
    imdbRating: "8.8",
    imdbVotes: "2,179,906",
    imdbID: "tt1375666",
    Type: "movie",
    DVD: "07 Dec 2010",
    BoxOffice: "$292,576,195",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];

export default data;
